import AnimatedText from '@/components/AnimatedText'
import HireMe from '@/components/HireMe'
import Layout from '@/components/Layout'
import TransitionEffects from '@/components/TransitionEffects'
import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import LINEA from '../../public/images/imagenes_vga/linea_blanca.png'
import COLDTECH  from '../../public/images/imagenes_vga/coldtech.png';
import lightBlub from '../../public/images/svgs/miscellaneous_icons_1.svg'

import {motion} from 'framer-motion'
import {Frezz, WhatsApp2, Telefono} from '../components/Icons'



export default function Home() {
  return (
    <>
      <Head>
        <title>VGA-Service</title>
        <meta name="description" content="Generated by Javier Mills" />
      </Head>
      <TransitionEffects />
     <main className='flex items-center text-dark dark:text-light w-full min-h-screen'>
       <Layout className='pt-0 md:pt-16 sm:pt-8'>

        <div className='flex items-center justify-between w-full lg:flex-col'>
          <div className='w-1/2 md:w-full'>
            {/* priority hace que cuando se carge la paguina la imagen tenga una alta prioridad en mostrarse  */}
            <Image src={LINEA} alt="Javier Mills" className='w-full h-auto p-3 lg:hidden md:inline-block md:w-full'
             priority sizes="(max-width: 768px) 100vw,
              (max-width: 1200px) 50vw, 50vw"/>
          </div>
          {/* Contenedor que alvergara los botones asi como el texto animado  */}
          <div className='w-1/2 flex flex-col items-center self-center lg:w-full lg:text-center'>
            {/* Colocamos el texto animado  */}

            <AnimatedText title="Ingeniería en Sistemas Integrales." 
            className='!text-6xl !text-left xl:!text-5xl lg:!text-center lg:!text-6xl 
            md:!text-5xl sm:!text-3xl'/>
            {/* Colocamos el texto que no estara animado  */}
            <p className='my-4 text-base font-medium md:text-sm sm:text-xs'>
             Nos enfocamos en el diseño, desarrollo, implementación y mantenimiento de sistemas complejos
              que integran mecanismos electricos tales como:
             
            </p>

            <div className='my-4 text-base font-medium md:text-sm sm:text-xs'>
             
             <div className='flex flex-wrap'>

                  <div className='flex justify-center'>
                    <motion.a  whileHover={{y: -3}}  whileTap={{scale:0.9}} className="w-4 mx-3"> <Frezz/></motion.a>
                    <motion.p  whileHover={{y: -3}}  whileTap={{scale:0.9}}>Modelos avanzados como no-frost, duplex, french door, CouldTech, etc.</motion.p></div>
                  <div className='flex justify-center'>
                  <motion.a  whileHover={{y: -3}}  whileTap={{scale:0.9}} className="w-4 mx-3"> <Frezz/></motion.a>
                  <motion.p  whileHover={{y: -3}}  whileTap={{scale:0.9}}>Refrigeradores domésticos (clásicos, análogos, digitales)</motion.p></div>
                  <div className='flex justify-center'>
                  <motion.a  whileHover={{y: -3}}  whileTap={{scale:0.9}} className="w-4 mx-3"> <Frezz/></motion.a>
                  <motion.p  whileHover={{y: -3}}  whileTap={{scale:0.9}}>Mini bares, frigos, air systems, cooler master, inverter, minisplits y más...</motion.p></div>
              </div> 
           </div>

            <div className='my-4 text-base font-medium md:text-sm sm:text-xs'>
             
              Contamos con personal y equipo que están capacitados para analizar, he implementar soluciones 
              integrales que satisfagan las necesidades de las organizaciones y los usuarios, recibe la cotizacion desde la comodidad de tu casa.              
            </div>


           
            <p className='text-transparent bg-clip-text bg-gradient-to-r from-[#48b6f4] from-10% via-[#24c8ff] via-35%  to-[#fd823b] to-60%  text-4xl mb-8'>
              <strong >¡27 años de experiencia nos respaldan!</strong></p>
            {/* Colocamos lo botones  */}
            {/* gradiente boton playgraoundIA */}
            {/* bg-gradient-to-r from-violet-500 from-0.71% via-red-400 from-49.65 to-orange-400 to-100% */}

            <div className='flex items-center self-start mt-2 lg:self-center'>
              <Link href="https://wa.me/5533824406?text=Hola buen dia, me interasa hacer una cotizacion " target={"_blank"} 
              className="flex items-center bg-green-500 text-light p-2.5 px-6
              rounded-lg text-lg font-semibold hover:bg-light hover:text-dark border border-solid border-transparent 
              hover:border-dark dark:bg-light dark:text-dark hover:dark:bg-dark hover:dark:text-light
              hover:dark:border-light md:p-2 md:px-4 md:text-base
              " download={true}>Contactanos<WhatsApp2 className={"w-6 ml-1"}/></Link>


            <div className='md:flex md:justify-center md:flex-wrap'>
            <Link href='tel:5645402895' className="ml-11 sm:pb-3 text-lg forn-medium capitalize text-red-500 dark:text-light md:text-base no-underline flex font-extrabold"> 
              <div className='flex justify-center'>
                <div className='flex justify-center font-extrabold sm:text-xs'>
                  <Telefono className={"w-7 ml-1 sm:w-6"}/>
                  &nbsp;
                  <h2>56 4540 2895</h2> 
                  </div> 
              </div>
              </Link>

              <Link href='tel:5645402895' className="ml-11 text-lg forn-medium capitalize text-red-500 dark:text-light md:text-base no-underline flex font-extrabold"> 
              <div className='flex justify-center'>
                <div className='flex justify-center font-extrabold sm:text-xs'>
                  <Telefono className={"w-7 ml-1 sm:w-6"}/>
                  &nbsp;
                  <h2>55 1701 8132</h2> 
                  </div> 
              </div>
              
              </Link>
            </div>
              
            </div>
          </div>
        </div>

       </Layout>
       {/* Boton de HireMe que estara dando vueltas  */}
       <HireMe />
       <div className='absolute right-8 bottom-8 inline-block w-24'>
         {/* Colocamos la imagen del foco  */}
    <Image src={lightBlub} alt="JavierMills" className="w-full h-auto- md:hidden"/>
       </div>
     </main>
    </>
  )
}
